
service: db-restore

provider:
  name: aws
  runtime: python3.7
  stage: dev
#  region: us-east-1
  environment:
    DB_NAME: ${file(./config.${self:custom.stage}.yml):DB_NAME}
    DB_RESOURCE_ARN: ${file(./config.${self:custom.stage}.yml):DB_RESOURCE_ARN}
    DB_SECRET_ARN: ${file(./config.${self:custom.stage}.yml):DB_SECRET_ARN}
    DB_FILE_URL: ${file(./config.${self:custom.stage}.yml):DB_FILE_URL}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - rds-data:ExecuteStatement
      - rds-data:BeginTransaction
      - rds-data:CommitTransaction
    Resource: "*"
  - Effect: Allow
    Action:
      - secretsmanager:GetSecretValue
    Resource: ${self:provider.environment.DB_SECRET_ARN}


functions:
  restoreDb:
    handler: handler.download_restore_db
    timeout: 900


resources:


plugins:
  - serverless-python-requirements


custom:
  stage: ${opt:stage, self:provider.stage}
  pythonRequirements:
    dockerizePip: non-linux